openapi: 3.0.3
info:
  title: Tasks
  description: Tasks API
  version: 0.0.1
paths:
  /tasks:
    get:
      tags:
        - tasks
      description: returns all of the tasks
      responses:
        '200':
          description: all of the tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      operationId: create
      tags:
        - tasks
      description: create a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: program created successfully
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 350
        status:
          type: boolean