openapi: 3.0.3
info:
  title: Tasks
  description: Tasks API
  version: 0.0.1
paths:
  /tasks:
    get:
      tags:
        - tasks
      description: returns all of the tasks
      responses:
        '200':
          description: all of the tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64